site_name: scaliir.de
site_url: https://www.scaliir.de/

theme:
  name: material
  logo: favicon.png
  favicon: favicon.png
  custom_dir: overrides
  palette:
    scheme: default
  features:
  - navigation.indexes
  - toc.follow
  - content.code.copy

plugins:
  - search
  - meta
#  - optimize
  - tags
  - blog:
      authors: false
      archive: false
      blog_toc: true
      post_readtime_words_per_minute: 265

# repo_url: https://github.com/scaliir/main

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
