site_name: scaliir.de
site_url: https://www.scaliir.de/

theme:
  name: material
  logo: favicon.png
  favicon: favicon.png
  custom_dir: overrides
  palette:
    scheme: default
  features:
  - navigation.indexes
  - toc.follow

plugins:
  - search
  - meta
#  - optimize
  - tags
  - blog:
      authors: false
      archive: true
      blog_toc: true
      post_readtime_words_per_minute: 265

# repo_url: https://github.com/scaliir/main

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true